
parameters:
  project_url: https://github.com/schulit/idp

common:
  app:
    url: "%env(APP_URL)%"
    name: "%env(APP_NAME)%"
    version: "%version%"
    project_url: "%project_url%"
    logo: "%env(APP_LOGO)%"
    small_logo: "%env(APP_SMALLLOGO)%"
    logo_link: 'dashboard'
  locales: "%locales%"
  menu: mainMenu
  disable:
    autoconfig: true
    cron: true
