version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.local
    volumes:
      - certs:/var/www/html/certs
      # nginx configuration file
      # - ./nginx.conf:/etc/nginx/sites-enabled/default

  db:
    image: mariadb:10.4
    restart: always
    env_file:
      - .env.local
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  db_data:
  certs:


