name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  release:
    types: [ published ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: simonfrank
  # github.repository as <account>/<repo>
  IMAGE_NAME: schulit-idp

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
   # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image to nightly
        id: build-and-push-nightly
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:nightly
          labels: ${{ steps.meta.outputs.labels }}
          build-args: version_info=${{ env.RELEASE_VERSION }} (${{ env.CURRENT_DATE }})
      - name: Build and push Docker image to latest
        if: ${{ !github.event.release.prerelease && github.event_name != 'push' }}
        id: build-and-push-latest
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: version_info=${{ env.RELEASE_VERSION }} (${{ env.CURRENT_DATE }})

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image to ${{ env.RELEASE_VERSION }} and unstable
        if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
        id: build-and-push-tag
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }} , ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:unstable
          labels: ${{ steps.meta.outputs.labels }}
          build-args: version_info=${{ env.RELEASE_VERSION }} (${{ env.CURRENT_DATE }})
